
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CATEGORY CLOSE_DATA CLOSE_TITLE CONTENT NAME OPEN_DATA OPEN_TITLE START STYLE TITLE X_AXISstart_d : OPEN_TITLE TITLE CLOSE_TITLE skip_tagskip_tag : STYLE skip_tag\n                | CONTENT skip_tag\n                | X_AXIS CATEGORY get_dateget_date : CONTENT CLOSE_DATA CLOSE_TITLE skip_tag1skip_tag1 : STYLE skip_tag1\n                 | CONTENT skip_tag1\n                 | CLOSE_DATA skip_tag1\n                 | startstart : START NAME get_dataget_data : STYLE get_data\n                | OPEN_DATA get_contentget_content : CONTENT CLOSE_DATA'
    
_lr_action_items = {'OPEN_TITLE':([0,],[2,]),'$end':([1,5,9,10,12,18,20,22,23,24,26,29,30,32,],[0,-1,-2,-3,-4,-5,-9,-7,-8,-6,-10,-11,-12,-13,]),'TITLE':([2,],[3,]),'CLOSE_TITLE':([3,14,],[4,15,]),'STYLE':([4,6,7,15,16,17,19,25,27,],[6,6,6,19,19,19,19,27,27,]),'CONTENT':([4,6,7,11,15,16,17,19,28,],[7,7,7,13,16,16,16,16,31,]),'X_AXIS':([4,6,7,],[8,8,8,]),'CATEGORY':([8,],[11,]),'CLOSE_DATA':([13,15,16,17,19,31,],[14,17,17,17,17,32,]),'START':([15,16,17,19,],[21,21,21,21,]),'NAME':([21,],[25,]),'OPEN_DATA':([25,27,],[28,28,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start_d':([0,],[1,]),'skip_tag':([4,6,7,],[5,9,10,]),'get_date':([11,],[12,]),'skip_tag1':([15,16,17,19,],[18,22,23,24,]),'start':([15,16,17,19,],[20,20,20,20,]),'get_data':([25,27,],[26,29,]),'get_content':([28,],[30,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start_d","S'",1,None,None,None),
  ('start_d -> OPEN_TITLE TITLE CLOSE_TITLE skip_tag','start_d',4,'p_start_d','activecases.py',61),
  ('skip_tag -> STYLE skip_tag','skip_tag',2,'p_skip_tag','activecases.py',64),
  ('skip_tag -> CONTENT skip_tag','skip_tag',2,'p_skip_tag','activecases.py',65),
  ('skip_tag -> X_AXIS CATEGORY get_date','skip_tag',3,'p_skip_tag','activecases.py',66),
  ('get_date -> CONTENT CLOSE_DATA CLOSE_TITLE skip_tag1','get_date',4,'p_get_date','activecases.py',69),
  ('skip_tag1 -> STYLE skip_tag1','skip_tag1',2,'p_skip_tag1','activecases.py',73),
  ('skip_tag1 -> CONTENT skip_tag1','skip_tag1',2,'p_skip_tag1','activecases.py',74),
  ('skip_tag1 -> CLOSE_DATA skip_tag1','skip_tag1',2,'p_skip_tag1','activecases.py',75),
  ('skip_tag1 -> start','skip_tag1',1,'p_skip_tag1','activecases.py',76),
  ('start -> START NAME get_data','start',3,'p_start','activecases.py',79),
  ('get_data -> STYLE get_data','get_data',2,'p_get_data','activecases.py',82),
  ('get_data -> OPEN_DATA get_content','get_data',2,'p_get_data','activecases.py',83),
  ('get_content -> CONTENT CLOSE_DATA','get_content',2,'p_get_content','activecases.py',86),
]
