
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CLOSEP CONTENT DATE OPENP\n    content : CONTENT content\n            | DATE content\n            | \n    \n    start : OPENP DATE content CLOSEP\n          | DATE content CLOSEP\n    '
    
_lr_action_items = {'CONTENT':([0,2,3,],[2,2,2,]),'DATE':([0,2,3,],[3,3,3,]),'$end':([0,1,2,3,4,5,],[-3,0,-3,-3,-1,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'content':([0,2,3,],[1,4,5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> content","S'",1,None,None,None),
  ('content -> CONTENT content','content',2,'p_content','2022.py',38),
  ('content -> DATE content','content',2,'p_content','2022.py',39),
  ('content -> <empty>','content',0,'p_content','2022.py',40),
  ('start -> OPENP DATE content CLOSEP','start',4,'p_start','2022.py',51),
  ('start -> DATE content CLOSEP','start',3,'p_start','2022.py',52),
]
