
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CATEGORY CLOSEDATA CLOSETITLE CONTENT NAME OPENDATA OPENTITLE START STYLE TITLE XAXISstart_d : OPENTITLE TITLE CLOSETITLE skiptagskiptag : STYLE skiptag\n               | CONTENT skiptag\n               | XAXIS CATEGORY getdategetdate : CONTENT CLOSEDATA CLOSETITLE skiptag1skiptag1 : STYLE skiptag1\n                | CONTENT skiptag1\n                | OPENDATA skiptag1\n                | CLOSEDATA skiptag1\n                | CLOSETITLE skiptag1\n                | startstart : NAME getdata\n             | START NAME getdata\n             | START skiptag1getdata : STYLE getdata\n               | OPENDATA getcontentgetcontent : CONTENT CLOSEDATA'
    
_lr_action_items = {'OPENTITLE':([0,],[2,]),'$end':([1,5,9,10,12,19,22,25,26,27,28,29,30,34,35,36,38,39,],[0,-1,-2,-3,-4,-5,-11,-7,-9,-10,-6,-8,-12,-14,-15,-16,-12,-17,]),'TITLE':([2,],[3,]),'CLOSETITLE':([3,14,15,16,17,18,20,21,24,],[4,15,18,18,18,18,18,18,18,]),'STYLE':([4,6,7,15,16,17,18,20,21,23,24,31,33,],[6,6,6,20,20,20,20,20,20,31,20,31,31,]),'CONTENT':([4,6,7,11,15,16,17,18,20,21,24,32,],[7,7,7,13,16,16,16,16,16,16,16,37,]),'XAXIS':([4,6,7,],[8,8,8,]),'CATEGORY':([8,],[11,]),'CLOSEDATA':([13,15,16,17,18,20,21,24,37,],[14,17,17,17,17,17,17,17,39,]),'OPENDATA':([15,16,17,18,20,21,23,24,31,33,],[21,21,21,21,21,21,32,21,32,32,]),'NAME':([15,16,17,18,20,21,24,],[23,23,23,23,23,23,33,]),'START':([15,16,17,18,20,21,24,],[24,24,24,24,24,24,24,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start_d':([0,],[1,]),'skiptag':([4,6,7,],[5,9,10,]),'getdate':([11,],[12,]),'skiptag1':([15,16,17,18,20,21,24,],[19,25,26,27,28,29,34,]),'start':([15,16,17,18,20,21,24,],[22,22,22,22,22,22,22,]),'getdata':([23,31,33,],[30,35,38,]),'getcontent':([32,],[36,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start_d","S'",1,None,None,None),
  ('start_d -> OPENTITLE TITLE CLOSETITLE skiptag','start_d',4,'p_start_d','newCases.py',60),
  ('skiptag -> STYLE skiptag','skiptag',2,'p_skiptag','newCases.py',63),
  ('skiptag -> CONTENT skiptag','skiptag',2,'p_skiptag','newCases.py',64),
  ('skiptag -> XAXIS CATEGORY getdate','skiptag',3,'p_skiptag','newCases.py',65),
  ('getdate -> CONTENT CLOSEDATA CLOSETITLE skiptag1','getdate',4,'p_getdate','newCases.py',68),
  ('skiptag1 -> STYLE skiptag1','skiptag1',2,'p_skiptag1','newCases.py',72),
  ('skiptag1 -> CONTENT skiptag1','skiptag1',2,'p_skiptag1','newCases.py',73),
  ('skiptag1 -> OPENDATA skiptag1','skiptag1',2,'p_skiptag1','newCases.py',74),
  ('skiptag1 -> CLOSEDATA skiptag1','skiptag1',2,'p_skiptag1','newCases.py',75),
  ('skiptag1 -> CLOSETITLE skiptag1','skiptag1',2,'p_skiptag1','newCases.py',76),
  ('skiptag1 -> start','skiptag1',1,'p_skiptag1','newCases.py',77),
  ('start -> NAME getdata','start',2,'p_start','newCases.py',80),
  ('start -> START NAME getdata','start',3,'p_start','newCases.py',81),
  ('start -> START skiptag1','start',2,'p_start','newCases.py',82),
  ('getdata -> STYLE getdata','getdata',2,'p_getdata','newCases.py',85),
  ('getdata -> OPENDATA getcontent','getdata',2,'p_getdata','newCases.py',86),
  ('getcontent -> CONTENT CLOSEDATA','getcontent',2,'p_getcontent','newCases.py',89),
]
