
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CLOSE_HEADER CLOSE_LIST CLOSE_PARA CLOSE_SPAN CLOSE_TABLE CONTENT FIG_CAPTION_CLOSE FIG_CAPTION_OPEN GARBAGE OPEN_HEADER OPEN_LIST OPEN_PARA OPEN_SPAN OPEN_TABLE WRONG_DATAstart : tablehandle_header : OPEN_HEADER content CLOSE_HEADER  content handle_fig handle_header\n                     | OPEN_HEADER content CLOSE_HEADER   handle_fig content  handle_header\n                     | OPEN_HEADER content CLOSE_HEADER  content handle_header\n                     | OPEN_HEADER \n                     | handle_list handle_header\n                     | empty\n                     \n    handle_fig : FIG_CAPTION_OPEN skip FIG_CAPTION_CLOSE handle_fig\n                |\n    \n    skip :  CONTENT skip\n          | OPEN_LIST skip\n          | CLOSE_LIST skip\n          | empty\n    \n    handle_list : OPEN_LIST content handle_list CLOSE_LIST handle_list\n                 | OPEN_LIST content CLOSE_LIST handle_list\n                 | content handle_list\n                 | empty\n    content :  CONTENT content\n               | emptytable : OPEN_TABLE content CLOSE_HEADER handle_header  CLOSE_TABLE\n             | OPEN_TABLE handle_header  CLOSE_TABLE\n    empty :'
    
_lr_action_items = {'OPEN_TABLE':([0,],[3,]),'$end':([1,2,15,26,],[0,-1,-21,-20,]),'CONTENT':([3,4,6,7,8,9,10,11,12,13,14,16,17,20,21,23,25,27,28,29,30,31,32,34,36,37,38,40,43,47,],[6,6,6,-17,6,6,6,6,6,-16,-17,-18,-19,-17,6,6,6,6,6,36,6,-15,6,6,36,36,36,-14,-9,-8,]),'OPEN_HEADER':([3,4,6,7,9,11,12,13,14,16,17,20,23,25,27,28,30,31,32,34,40,43,47,],[8,-22,-22,-17,8,-22,8,-16,-17,-18,-19,-17,-9,-22,8,-22,-22,-15,8,8,-14,-9,-8,]),'CLOSE_HEADER':([3,4,6,7,8,16,17,18,],[-22,12,-22,-19,-22,-18,-19,23,]),'OPEN_LIST':([3,4,6,7,9,10,11,12,13,14,16,17,20,21,23,25,27,28,29,30,31,32,34,36,37,38,40,43,47,],[10,10,-22,-17,10,-22,10,10,-16,-17,-18,-19,-17,10,-9,10,10,-22,37,10,-15,10,10,37,37,37,-14,-9,-8,]),'CLOSE_TABLE':([3,4,5,6,7,8,9,11,12,13,14,16,17,19,20,22,23,25,27,28,30,31,32,33,34,40,41,42,43,47,],[-22,-22,15,-22,-7,-5,-22,-22,-22,-16,-17,-18,-19,-6,-7,26,-9,-22,-9,-22,-22,-15,-22,-4,-22,-14,-2,-3,-9,-8,]),'CLOSE_LIST':([6,10,11,13,14,16,17,21,24,25,29,30,31,36,37,38,40,],[-22,-22,-22,-16,-17,-18,-19,25,30,-22,38,-22,-15,38,38,38,-14,]),'FIG_CAPTION_OPEN':([6,16,17,23,27,43,],[-22,-18,-19,29,29,29,]),'FIG_CAPTION_CLOSE':([29,35,36,37,38,39,44,45,46,],[-22,43,-22,-22,-22,-13,-10,-11,-12,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'table':([0,],[2,]),'content':([3,4,6,8,9,10,11,12,21,23,25,27,28,30,32,34,],[4,11,16,18,11,21,11,11,11,27,11,11,34,11,11,11,]),'handle_header':([3,9,12,27,32,34,],[5,19,22,33,41,42,]),'empty':([3,4,6,8,9,10,11,12,21,23,25,27,28,29,30,32,34,36,37,38,],[7,14,17,17,20,17,14,20,14,17,14,20,17,39,14,20,20,39,39,39,]),'handle_list':([3,4,9,11,12,21,25,27,30,32,34,],[9,13,9,13,9,24,31,9,40,9,9,]),'handle_fig':([23,27,43,],[28,32,47,]),'skip':([29,36,37,38,],[35,44,45,46,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> table','start',1,'p_start','getNews.py',88),
  ('handle_header -> OPEN_HEADER content CLOSE_HEADER content handle_fig handle_header','handle_header',6,'p_handle_header','getNews.py',98),
  ('handle_header -> OPEN_HEADER content CLOSE_HEADER handle_fig content handle_header','handle_header',6,'p_handle_header','getNews.py',99),
  ('handle_header -> OPEN_HEADER content CLOSE_HEADER content handle_header','handle_header',5,'p_handle_header','getNews.py',100),
  ('handle_header -> OPEN_HEADER','handle_header',1,'p_handle_header','getNews.py',101),
  ('handle_header -> handle_list handle_header','handle_header',2,'p_handle_header','getNews.py',102),
  ('handle_header -> empty','handle_header',1,'p_handle_header','getNews.py',103),
  ('handle_fig -> FIG_CAPTION_OPEN skip FIG_CAPTION_CLOSE handle_fig','handle_fig',4,'p_handle_fig','getNews.py',120),
  ('handle_fig -> <empty>','handle_fig',0,'p_handle_fig','getNews.py',121),
  ('skip -> CONTENT skip','skip',2,'p_skip','getNews.py',127),
  ('skip -> OPEN_LIST skip','skip',2,'p_skip','getNews.py',128),
  ('skip -> CLOSE_LIST skip','skip',2,'p_skip','getNews.py',129),
  ('skip -> empty','skip',1,'p_skip','getNews.py',130),
  ('handle_list -> OPEN_LIST content handle_list CLOSE_LIST handle_list','handle_list',5,'p_handle_list','getNews.py',136),
  ('handle_list -> OPEN_LIST content CLOSE_LIST handle_list','handle_list',4,'p_handle_list','getNews.py',137),
  ('handle_list -> content handle_list','handle_list',2,'p_handle_list','getNews.py',138),
  ('handle_list -> empty','handle_list',1,'p_handle_list','getNews.py',139),
  ('content -> CONTENT content','content',2,'p_content','getNews.py',152),
  ('content -> empty','content',1,'p_content','getNews.py',153),
  ('table -> OPEN_TABLE content CLOSE_HEADER handle_header CLOSE_TABLE','table',5,'p_table','getNews.py',164),
  ('table -> OPEN_TABLE handle_header CLOSE_TABLE','table',3,'p_table','getNews.py',165),
  ('empty -> <empty>','empty',0,'p_empty','getNews.py',170),
]
