
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CLOSEP CONTENT DATE OPENP\n    start : OPENP DATE content CLOSEP\n          | DATE content CLOSEP\n    \n    content : CONTENT content\n            | DATE content\n            | \n    '
    
_lr_action_items = {'OPENP':([0,],[2,]),'DATE':([0,2,3,4,5,7,],[3,4,5,5,5,5,]),'$end':([1,10,12,],[0,-2,-1,]),'CONTENT':([3,4,5,7,],[7,7,7,7,]),'CLOSEP':([3,4,5,6,7,8,9,11,],[-5,-5,-5,10,-5,12,-4,-3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'content':([3,4,5,7,],[6,8,9,11,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> OPENP DATE content CLOSEP','start',4,'p_start','2020.py',37),
  ('start -> DATE content CLOSEP','start',3,'p_start','2020.py',38),
  ('content -> CONTENT content','content',2,'p_content','2020.py',59),
  ('content -> DATE content','content',2,'p_content','2020.py',60),
  ('content -> <empty>','content',0,'p_content','2020.py',61),
]
